[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  POSTGRES_URL = "placeholder" # This will be overridden by Netlify's environment variables
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
